# Generated by Django 4.2.7 on 2023-11-21 19:04

import django.core.validators
from django.db import migrations, models
import student_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[student_app.validators.validate_name])),
                ('student_email', models.EmailField(max_length=254, unique=True, validators=[student_app.validators.validate_student_email])),
                ('personal_email', models.EmailField(max_length=254, unique=True)),
                ('locker_number', models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('locker_combination', models.CharField(default='12-12-12', validators=[student_app.validators.validate_locker_combination])),
                ('good_student', models.BooleanField(default=True)),
            ],
        ),
    ]
