# Generated by Django 4.2.7 on 2023-11-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
