# Generated by Django 4.2.7 on 2023-11-21 20:12

import django.core.validators
from django.db import migrations, models
import student_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_alter_student_locker_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='locker_number',
            field=models.IntegerField(default=110, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(max_length=254, unique=True, validators=[student_app.validators.validate_student_email]),
        ),
    ]
