# Generated by Django 4.2.7 on 2023-11-21 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=1)),
                ('date_encountered', models.DateField(default='2008-01-01')),
                ('date_captured', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(default='Unknown')),
                ('captured', models.BooleanField(default=False)),
            ],
        ),
    ]
