# Generated by Django 4.2.7 on 2023-11-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name': 'pokemon'},
        ),
    ]
