# Generated by Django 4.2.7 on 2023-11-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0002_alter_pokemon_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name_plural': 'pokemon'},
        ),
    ]
