# Generated by Django 4.2.7 on 2023-11-21 16:16

from django.db import migrations, models
import pokedex_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0004_alter_pokemon_description_alter_pokemon_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=255, validators=[pokedex_app.validators.validate_name]),
        ),
    ]
