# Generated by Django 4.2.7 on 2023-11-22 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0007_pokedex_trainer_pokemon_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='pokedex',
        ),
        migrations.AddField(
            model_name='pokedex',
            name='trainer',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex_app.trainer'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='gym_badges',
            field=models.IntegerField(default=0),
        ),
    ]
